### ISSUE TITLE
Make a maintenance release for Win32 compatibility improvements

### ISSUE THREAD

**Issue by dmbaturin** [gildor478/ocaml-fileutils#10]
Could you make a 0.5.4 maintenance release for the Win32 compatibility improvements so that it can be added to opam-cross-windows and native repos?

With all three PRs merged, it builds and passes the tests, and things I wanted a cross-platform library for (path manipulation, mkdir, Exists, rm, a few others) work fine. There may be more Win32 "peculiarities" to add fixups for, but it's a lot better than nothing I think.
If people find and report more bugs, I'll try to help fixing them too.

**Comment by gildor478** [comment]
The release:
https://github.com/gildor478/ocaml-fileutils/releases/tag/v0.6.0

OPAM pull request:
https://github.com/ocaml/opam-repository/pull/14739

Thanks for all.

**Comment by dmbaturin** [comment]
Thanks! Will you make pull requests to opam-windows and opam-cross-windows, or should I?

**Comment by gildor478** [comment]
@dmbaturin 
Please do the pull requests and CC-me, so that I know where to do them next time.

Thanks
