### ISSUE TITLE
FilePath.get_extension raises Not_found when a file has no extension

### ISSUE THREAD

**Issue by dmbaturin** [gildor478/ocaml-fileutils#12]
The `FilePath.get_extension` function raises `Not_found` when a file has no extension. It's not a problem by itself, of course. The problem is that:

* that behaviour is udocumented
* it's also unintuitive because all other functions return an empty string in that situation:

```
utop # FilePath.dirname "ocamlc" ;;
- : string = ""

utop # FilePath.basename "/" ;;
- : string = ""

utop # FilePath.chop_extension "ocamlc" ;;
- : string = "ocamlc"

utop # FilePath.get_extension "ocamlc";;
Exception: Not_found.
```

Do you consider that a bug or intended behaviour? I'm ready to make a patch for either changing it or documenting it.

**Comment by gildor478** [comment]
It is made on purpose and I would appreciate a documention patch. 

AFAIR, dirname/basename should be reverted by concat:

What
```
# let fn = "/" in fn = FilePath.concat (FilePath.dirname fn) (FilePath.basename fn);;
- : bool = true
#  let fn = "ocamlc"  in fn = FilePath.concat (FilePath.dirname fn) (FilePath.basename fn);;
- : bool = true
```

And for extension, chop_extension/get_extension should be reverted by add:
```
# let fn = "ocamlc.exe" in fn = FilePath.add_extension (FilePath.chop_extension fn) (FilePath.get_extension fn);;
- : bool = true
```

When there is no extension, I don't think there is a sane value to return so I decided to raise an exception.

**Comment by dmbaturin** [comment]
Well, if I'm arguing with you about the design of _your_ library... :)
I'm not sure if behaviour of `add_extension` with empty string is sensible.

```
# FilePath.add_extension "foo" "" ;;
- : string = "foo."

```
If `FilePath.add_extension "name" ""` returned `"name"`, that invariant would hold. 

There may also be valid uses for adding an empty extension. For example, a program may provide a configurable option for default extension of its output files, in that case it would be easy to give users ability not to add any extension by setting that option to an empty string (or setting it a null value and coercing that value to an empty string behind the scenes).

In any case, `foo.` is unlikely to be the result anyone would want. I believe it should either _also_ raise an exception, or interpret empty string as "do nothing".

If you insist on keeping the original behaviour, I'll send a documentation patch.

**Comment by gildor478** [comment]
I think the original behavior is good enough.

**Comment by dmbaturin** [comment]
Ok, I've updated the documentation to clarify that behaviour (#13).

**Comment by dmbaturin** [comment]
Closing since #13 is merged.
