### ISSUE TITLE
Fileutils broken with OCaml 4.06.0

### ISSUE THREAD

**Issue by maelvalais** [gildor478/ocaml-fileutils#5]
Dear Sylvain,

Something seems to have broken `fileutils` in OCaml 4.06.0 (using `opam install fileutils` on a fresh opam install).

I think that the deprecation notice related to the migration from `string` to `bytes` has now become an error.

<details>   <summary>output of build</summary>
<pre>
ocamlopt.opt unix.cmxa -I /Users/mvalais/.opam/system/lib/ocamlbuild /Users/mvalais/.opam/system/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /Users/mvalais/.opam/system/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "_tags", line 28, characters 18-27:
Warning: the tag "pkg_oUnit" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 33, characters 19-28:
Warning: the tag "pkg_oUnit" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtil.mli > src/FileUtil.mli.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FilePath.mli > src/FilePath.mli.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilMode.ml > src/FileUtilMode.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FilePath.cmi src/FilePath.mli
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilMode.cmo src/FileUtilMode.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtil.cmi src/FileUtil.mli
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtil.ml > src/FileUtil.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilCHMOD.ml > src/FileUtilCHMOD.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilLS.ml > src/FileUtilLS.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilMisc.ml > src/FileUtilMisc.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilTypes.ml > src/FileUtilTypes.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilTypes.cmo src/FileUtilTypes.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilMisc.cmo src/FileUtilMisc.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilPermission.ml > src/FileUtilPermission.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilSTAT.ml > src/FileUtilSTAT.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilPermission.cmo src/FileUtilPermission.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilUMASK.ml > src/FileUtilUMASK.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilLS.cmo src/FileUtilLS.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilSTAT.cmo src/FileUtilSTAT.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilUMASK.cmo src/FileUtilUMASK.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilCMP.ml > src/FileUtilCMP.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilTEST.ml > src/FileUtilTEST.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilSize.ml > src/FileUtilSize.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilSize.cmo src/FileUtilSize.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilTEST.cmo src/FileUtilTEST.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilCP.ml > src/FileUtilCP.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilCHMOD.cmo src/FileUtilCHMOD.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilMKDIR.ml > src/FileUtilMKDIR.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilRM.ml > src/FileUtilRM.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilTOUCH.ml > src/FileUtilTOUCH.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilMKDIR.cmo src/FileUtilMKDIR.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilRM.cmo src/FileUtilRM.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilTOUCH.cmo src/FileUtilTOUCH.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilDU.ml > src/FileUtilDU.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilFIND.ml > src/FileUtilFIND.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilREADLINK.ml > src/FileUtilREADLINK.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilPWD.ml > src/FileUtilPWD.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilPWD.cmo src/FileUtilPWD.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilREADLINK.cmo src/FileUtilREADLINK.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilFIND.cmo src/FileUtilFIND.ml
/Users/mvalais/.opam/system/bin/ocamlfind ocamldep -package str -package unix -modules src/FileUtilMV.ml > src/FileUtilMV.ml.depends
/Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilCP.cmo src/FileUtilCP.ml
+ /Users/mvalais/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package str -package unix -I src -o src/FileUtilCP.cmo src/FileUtilCP.ml
File "src/FileUtilCP.ml", line 179, characters 39-45:
Error: This expression has type string but an expression was expected of type
         bytes
Command exited with code 2.
</pre>
</details>

Best regards,
Maël

**Comment by maelvalais** [comment]
It would probably need something like `cppo` in `src/FileUtilCP.ml`:

```
#if OCAML_VERSION >= (4, 6, 0)
let buffer = Bytes.make 1024 ' ' in
#else
let buffer = String.make 1024 ' ' in
#endif
```

**Comment by gildor478** [comment]
Fixed in the release:
https://github.com/gildor478/ocaml-fileutils/releases/tag/0.5.3

OPAM release:
https://github.com/ocaml/opam-repository/pull/10669

**Comment by maelvalais** [comment]
Thanks so much!!! :)
